sonar.projectKey=notes-app-backend
sonar.projectName=Notes App Backend
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js
sonar.exclusions=node_modules/**,coverage/**
sonar.sourceEncoding=UTF-8